### ISSUE TITLE
Apache can not start

### ISSUE THREAD

**Issue by AndzinSan** [smart-mobile-software/gitstack#91] opened 2012-05-21 19:03 UTC
I install actual version 2.0.2 by installer from home page. Install dir is set to F:\GitStack.
Here are some errors:

1) in httpd.conf on line 480 is this:

> > > SSLSessionCache shm:C:/dev/apache/logs/ssl_cache_shm

but this line causes that apache can not start. This line should look like this (in my case):

> > > SSLSessionCache shm:F:/GitStack/apache/logs/ssl_cache_shm

So, you should implement changing this line with instalation process.

2) When I fix error1 apache still not start. Why? I found this:
-running apache as service from services report error to event log, it looks like:

The Apache service named  reported the following error:

> > > httpd.exe: Syntax error on line 484 of F:/GitStack/apache/conf/httpd.conf: Cannot load F:/GitStack/apache/modules/mod_wsgi.so into server: Zadan\xfd modul sa nepodarilo n\xe1js\x9d.

This error appear when python is installed only for current user or (in this case) if python is not installed, just copied. So for fix this it needs to property install python. I.E. run included python instalation from Gitstack\python\python-2.7.2.msi and set instalation dir to Gitstack\python and owerwrite all files. Instalation must be set to install for all users.

Now, after success instalation of python apache works.
*While python instalation installer display dialog about some file can not be owerwriten, just click ignore!

Maybe here is another way how to force mod_wsgi.so work without python instalation, but I dond find anyone.

Another way how to "simulate" python instalation maybe insert proper variables to the windows registry. I gues that it can be this:

> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python]
> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore]
> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7]
> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\Help]
> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\Help\Main Python Documentation]
> > > @="F:\GitStack\python\Doc\python272.chm"
> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\InstallPath]
> > > @="F:\GitStack\python\"
> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\InstallPath\InstallGroup]
> > > @="Python 2.7"
> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\Modules]
> > > [HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\PythonPath]
> > > @="F:\GitStack\python\Lib;F:\GitStack\python\DLLs;F:\GitStack\python\Lib\lib-tk"

Most important registry variable is PythonPath. Without this, apache cant start.

So I recommend you to prepare instalator to add this registry entry while installation and edit line 480 in httpd.conf.

I hope this will help somebody. ;)

**Comment by poiuytrez** [comment] 2012-05-22 09:10
Hi,

Could you tell me the exact steps to reproduce the bug ?
Was python installed previously on your system ? 
Which operating system are you running ?

Thank you

**Comment by Kogasan** [comment] 2012-05-22 09:46
I test it on win XP and win 7 - both system was clear - no python installed before.
Exact steps? Just download last release instalator 2.0.2 and run it. Installation was succesfull.
Error 1 what I wrote appears only if you select another installation dir as C:/dev.
Error 2 what I wrote appears only if you dont have installed python, respectively ifyou dont have registry value:
[HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\PythonPath]
@="F:\GitStack\python\Lib;F:\GitStack\python\DLLs;F:\GitStack\python\Lib\lib-tk"

**Comment by poiuytrez** [comment] 2012-05-22 10:21
"Error 1 what I wrote appears only if you select another installation dir as C:/dev."
Please tell me exactly in which directory you tried to install the application. C:/dev works.

**Comment by Kogasan** [comment] 2012-05-22 11:47
In first post I wrote:

> Install dir is set to F:\GitStack.

**Comment by poiuytrez** [comment] 2012-05-23 15:09
Hi,

I have performed the test scenario today (install GitStack on a F: drive).
It is working. The issue should be somewhere else. Are you sure that you do not have any insight on where it can come from ?

http://i47.tinypic.com/2eutwtz.png

**Comment by AndzinSan** [comment] 2012-05-23 15:57
Hmm, I am very confuse now. I try repeat instalation (revert all changes what I do) but everythink is still working - no error. I dont know how or why but now it works without changings in httpd.conf or editing registry.

Maybe it is needed to restart computer? Yesterday when I was installing gitstack I didnt restart computer. Can be this that error source?

**Comment by poiuytrez** [comment] 2012-05-23 15:59
You usually do not have to restart the computer. I am glad that it now works on your system. I close the issue. Feel free to open it again if you find the root cause of the issue.

**Closed as completed by poiuytrez** 2012-05-23 15:59 UTC
